services:
- type: web
  name: line-bot-nodejs-echo
  env: node
  repo: https://github.com/line/line-bot-sdk-nodejs.git
  buildCommand: cd chatbot4;npm install
  startCommand: cd chatbot4;node .
  plan: free
  autoDeploy: false
  envVars:
  - key: CHANNEL_ACCESS_TOKEN
    sync: false
  - key: CHANNEL_SECRET
    sync: false
